version: '3.4'

services: 
certbot:
     image: certbot/certbot:latest
     command: certonly --webroot -w /usr/share/nginx/html/ -d test.niptict.edu.kh
     volumes:
       - ./certbot/conf/:/etc/letsencrypt
       - ./certbot/logs/:/var/log/letsencrypt
       - ./certbot/data:/usr/share/nginx/html/
  web:
    image: nginx:1.14.2-alpine
    restart: always
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d/
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/
    ports:
      - 80:80
      - 443:443
  
  
